export { default as NavigationTabs } from "./navigationTabs/index.vue";
export { default as MainBanner } from "./mainBanner/index.vue";
export { default as SpecialOffers } from "./specialOffers/index.vue";
export { default as LeasingBanner } from "./leasingBanner/index.vue";
export { default as LocalProducts } from "./localProducts/index.vue";
export { default as PopularCategories } from "./popularCategories/index.vue";
export { default as PopularBanners } from "./popularBanners/index.vue";
export { default as UsefulServices } from "./usefulServices/index.vue";
export { default as MediaList } from "./mediaList/index.vue";
