export const credits = [
  {
    id: 1,
    name: {
      uz: `"National Green"`,
      ru: `"National Green"`,
    },
    interest: 20,
    payment: 0,
    duration: 60,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 60000000,
    link: "https://nbu.uz/jismoniy-shaxslarga-kreditlar/national-green",
  },
  {
    id: 2,
    name: {
      uz: `"Tomorqa textnikasi" krediti`,
      ru: `кредит "Бытовая техника"`,
    },
    interest: 25,
    payment: 0,
    duration: 36,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 40000000,
    link: "https://sqb.uz/uz/individuals/credits/tomorqa-texnikasi-uz/",
  },
  {
    id: 3,
    name: {
      uz: `Eksportoldi moliyalashtirish`,
      ru: `Предэкспортное финансирование`,
    },
    interest: 27,
    payment: 0,
    duration: 12,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `Qisqa muddatli kreditlar`,
      ru: `Краткосрочные кредиты`,
    },
    interest: 27,
    payment: 0,
    duration: 12,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `"Yashil energiya" jismoniy shaxslar uchun`,
      ru: `«Зеленая энергия» для частных лиц`,
    },
    interest: 19.5,
    payment: 0,
    duration: 6,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 100000000,
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `MFSR-diversifikatsiya`,
      ru: `MFSR-диверсификация`,
    },
    interest: 19.5,
    payment: 0,
    duration: 6,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 100000000,
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
];
