export const credits = [
  {
    id: 1,
    name: {
      uz: `"National Green"`,
      ru: `"National Green"`,
    },
    interest: 20,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 60000000,
    currency: "UZS",
    link: "https://nbu.uz/jismoniy-shaxslarga-kreditlar/national-green",
  },
  {
    id: 2,
    name: {
      uz: `"Tomorqa textnikasi" krediti`,
      ru: `кредит "Бытовая техника"`,
    },
    interest: 25,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 40000000,
    currency: "UZS",
    link: "https://sqb.uz/uz/individuals/credits/tomorqa-texnikasi-uz/",
  },
  {
    id: 3,
    name: {
      uz: `Eksportoldi moliyalashtirish`,
      ru: `Предэкспортное финансирование`,
    },
    interest: { from: 0, to: 27 },
    payment: 0,
    duration: 12,
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    currency: "UZS",
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `Qisqa muddatli kreditlar`,
      ru: `Краткосрочные кредиты`,
    },
    interest: 27,
    payment: 0,
    duration: { from: 0, to: 12 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    currency: "UZS",
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `"Yashil energiya" jismoniy shaxslar uchun`,
      ru: `«Зеленая энергия» для частных лиц`,
    },
    interest: 19.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 100000000,
    currency: "UZS",
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `MFSR-diversifikatsiya 1-kredit liniyasi`,
      ru: `MFSR-диверсификация 1-я кредитная линия`,
    },
    interest: 6.5,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 500000,
    currency: "USD",
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 4,
    name: {
      uz: `MFSR-diversifikatsiya 2-kredit liniyasi`,
      ru: `MFSR-диверсификация 2-я кредитная линия`,
    },
    interest: 6.5,
    payment: 0,
    duration: { from: 0, to: 24 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 100000,
    currency: "USD",
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
];
