export const credits = [
  {
    id: 1,
    name: {
      uz: `"National Green"`,
      ru: `"National Green"`,
    },
    interest: 20,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 60000000,
    info: [
      { uz: "Kredit stavkasi - yillik 20%", ru: "Кредитная ставка - ежегодная 20%" },
      { uz: "Kredit miqdori 60 mln so'mgacha", ru: "Кредитная сумма 60 млн. сум" },
      { uz: "Kredit muddati - 5 yil", ru: "Срок кредита - 5 лет" },
    ],
    link: "https://nbu.uz/jismoniy-shaxslarga-kreditlar/national-green",
  },
  {
    id: 2,
    name: {
      uz: `"Tomorqa textnikasi" krediti`,
      ru: `кредит "Бытовая техника"`,
    },
    interest: 25,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 40000000,
    info: [
      { uz: "Kredit foiz stavkasi 25%", ru: "Кредитная ставка 25%" },
      { uz: "Kredit miqdori 40 mln so'mgacha", ru: "Кредитная сумма до 40 млн. сум" },
      { uz: "Kredit muddati - 36 oygacha", ru: "Срок кредита - до 36 месецев" },
    ],
    link: "https://sqb.uz/uz/individuals/credits/tomorqa-texnikasi-uz/",
  },
  {
    id: 3,
    name: {
      uz: `Eksportoldi moliyalashtirish`,
      ru: `Предэкспортное финансирование`,
    },
    interest: 27,
    payment: 0,
    duration: { from: 0, to: 12 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Kredit foiz stavkasi 27%", ru: "Кредитная ставка 27%" },
      { uz: "Kredit muddati - 12 oygacha", ru: "Срок кредита - до 12 месецев" },
    ],
    link: "https://www.asakabank.uz/uz/corporate-customers/home",
  },
  {
    id: 5,
    name: {
      uz: `"Yashil energiya" jismoniy shaxslar uchun`,
      ru: `«Зеленая энергия» для частных лиц`,
    },
    interest: 19.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 100000000,
    info: [
      { uz: "Kredit foiz stavkasi 19.5%", ru: "Кредитная ставка 19.5%" },
      { uz: "Kredit miqdori 100 mln so'mgacha", ru: "Кредитная сумма до 100 млн. сум" },
      { uz: "Muddati - 60 oy (imtiyozli davr - 6 oy)", ru: "Срок - 60 месяцев (льготный период - 6 месяцев)" },
    ],
    link: "https://agrobank.uz/uz/business/loans/green-energy-b2b",
  },
  {
    id: 6,
    name: {
      uz: `MFSR-diversifikatsiya 1-kredit liniyasi`,
      ru: `MFSR-диверсификация 1-я кредитная линия`,
    },
    interest: 6.5,
    payment: 0,
    duration: { from: 0, to: 120 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 6500000000,
    info: [
      { uz: "Kredit foizi 6.5%, Milliy valyutada 19%", ru: "Процентная ставка по кредиту 6,5%, 19% в национальной валюте" },
      { uz: "Kredit summasi 500 000 AQSH dollarigacha", ru: "Кредитная сумма до 500 000 долларов США" },
      { uz: "Kredit muddati - 120 oygacha", ru: "Срок кредита - до 120 месяцев" },
    ],
    link: "",
  },
  {
    id: 7,
    name: {
      uz: `MFSR-diversifikatsiya 2-kredit liniyasi`,
      ru: `MFSR-диверсификация 2-я кредитная линия`,
    },
    interest: 6.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 1298400000,
    info: [
      {
        uz: "Kredit foizi AQSH dollarida 6.5%, Milliy valyutada 19%",
        ru: "Процентная ставка по кредиту в долларах США 6.5%, 19% в национальной валюте",
      },
      { uz: "Kredit summasi 100 000 AQSH dollarigacha", ru: "Кредитная сумма до 100 000 долларов США" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "",
  },
  {
    id: 8,
    name: {
      uz: `Chorvachilik sohasini rivojlantirish`,
      ru: `Развитие сельского хозяйства`,
    },
    interest: 21,
    payment: 0,
    duration: { from: 0, to: 120 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 1298400000,
    info: [
      { uz: "Yillik foiz stavkasi 19%", ru: "Ежегодная ставка 19%" },
      { uz: "Miqdori - 1 mln. yevro ekvivalentigacha", ru: "Сумма - до 1 млн. евро эквивалента" },
      {
        uz: "Muddati - Investitsiya loyihalari uchun – 120 oygacha;	Aylanma mablag‘lar uchun – 18 oygacha",
        ru: "Срок - до 120 месяцев для инвестиционных проектов; до 18 месяцев для вложений",
      },
    ],
    link: "https://brb.uz/kreditlar/chorvachilikni-rivojlantirish-krediti",
  },
  {
    id: 9,
    name: {
      uz: `"Oʻzbekiston Respublikasi qishloq xoʻjaligini diversifikatsiya va modernizatsiya qilish” loyihasi (IFAD)`,
      ru: `Проект «Диверсификация и модернизация сельского хозяйства Республики Узбекистан» (МФСР)`,
    },
    interest: 10,
    payment: 0,
    duration: { from: 0, to: 120 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 4546487855,
    info: [
      { uz: "Foiz stavkasi 10% dan", ru: "Ставка от 10%" },
      { uz: "Kredit miqdori - 350 min AQSH dollari", ru: "Кредитная сумма - до 350 долларов США" },
      { uz: "Muddati - 10 yilgacha", ru: "Срок - до 10 лет" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/ifadmoder/",
  },
  {
    id: 10,
    name: {
      uz: `“Green energy”`,
      ru: `“Green energy”`,
    },
    interest: 20.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 5000000000,
    info: [
      { uz: "Foiz stavkasi 20.5%", ru: "Ставка 20.5%" },
      { uz: "Kredit miqdori - 5 mlrd so'mgacha", ru: "Кредитная сумма - до 5 млрд. сум" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/green-energy-3469/",
  },
  {
    id: 11,
    name: {
      uz: `Eksportni ragʻbatlantirish agentligining mablagʻlari hisobidan kreditlash`,
      ru: `Кредитование за счет средств Агентства по содействию экспорту`,
    },
    interest: 4,
    payment: 0,
    duration: { from: 0, to: 12 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Foiz stavkasi 4%", ru: "Ставка 4%" },
      { uz: "Kredit miqdori - loyiha qiymatidan", ru: "Сумма кредита - от стоимости проекта" },
      { uz: "Muddati - 12 oygacha", ru: "Срок - до 12 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/export-promotion-agency/",
  },
  {
    id: 12,
    name: {
      uz: `“IMKONIYAT” krediti`,
      ru: `Кредит "ИМКОНИЯТ"`,
    },
    interest: 19,
    payment: 0,
    duration: { from: 0, to: 84 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 300000000,
    info: [
      { uz: "Foiz stavkasi 19% dan", ru: "Ставка от 19%" },
      { uz: "Kredit miqdori - 300 mln. so’mgacha", ru: "Кредитная сумма - до 300 млн. сум" },
      { uz: "Muddati - 84 oygacha", ru: "Срок - до 84 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/imkoniyat-kredit/",
  },
  {
    id: 13,
    name: {
      uz: `Qishloq xo‘jaligini rivojlantirish uchun`,
      ru: `Для развития сельского хозяйства`,
    },
    interest: 25,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Foiz stavkasi 25% dan", ru: "Ставка от 25%" },
      { uz: "Kredit miqdori - loyiha qiymatidan", ru: "Сумма кредита - от стоимости проекта" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "https://mkbank.uz/uz/corporate/crediting/qishloq-xo-jaligini-rivojlantirish-uchun/",
  },
  {
    id: 14,
    name: {
      uz: `Mikrokredit`,
      ru: `Микрокредитование`,
    },
    interest: 4,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 340000000,
    info: [
      { uz: "Yillik foiz stavkasi - Bazaviy stavka + 4.0%", ru: "Ежегодная ставка - Базовая ставка + 4.0%" },
      { uz: "Kredit miqdori - 340 mln. so’mgacha", ru: "Кредитная сумма - до 340 млн. сум" },
      { uz: "Muddati - 3 yilgacha", ru: "Срок - до 3 лет" },
    ],
    link: "https://aloqabank.uz/uz/corporate/crediting/microloan-passport/",
  },
  {
    id: 15,
    name: {
      uz: `«Muqobil Energiya uchun» modulli krediti`,
      ru: `Модульный кредит «На альтернативную энергетику»`,
    },
    interest: 20.5,
    payment: 0,
    duration: { from: 0, to: 36 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: 1500000000,
    info: [
      { uz: "Yillik foiz stavkasi - 20.5% dan", ru: "Ежегодная ставка от 20.5%" },
      { uz: "Kredit miqdori - 1,5 mlrd. so’mgacha", ru: "Кредитная сумма - до 1,5 млрд. сум" },
      { uz: "Muddati - 36 oygacha", ru: "Срок - до 36 месяцев" },
    ],
    link: "https://aloqabank.uz/uz/corporate/crediting/muqobil-energiya-modulli-krediti/",
  },
  {
    id: 16,
    name: {
      uz: `Eksport`,
      ru: `Экспорт`,
    },
    interest: 4,
    payment: 0,
    duration: { from: 0, to: 12 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Foiz stavkasi - 4% gacha", ru: "Cтавка - до 4%" },
      { uz: "Kredit miqdori - Shartnomaga asosan", ru: "Кредитная сумма - в соответствии с договором" },
      { uz: "Muddati - 12 oygacha", ru: "Срок - до 12 месяцев" },
    ],
    link: "https://turonbank.uz/uz/corporate/crediting/eksport/",
  },
  {
    id: 17,
    name: {
      uz: `ECOPANEL`,
      ru: `ECOPANEL`,
    },
    interest: 20.5,
    payment: 0,
    duration: { from: 0, to: 60 },
    minRate: null,
    partiallySecured: false,
    noCollateral: false,
    preferentialRate: null,
    simplifiedDocuments: false,
    maxAmount: null,
    info: [
      { uz: "Foiz stavkasi - 20,5% gacha", ru: "Cтавка - до 20,5%" },
      { uz: "Kredit miqdori - Shartnomaga asosan", ru: "Кредитная сумма - в соответствии с договором" },
      { uz: "Muddati - 60 oygacha", ru: "Срок - до 60 месяцев" },
    ],
    link: "https://turonbank.uz/uz/corporate/crediting/ecopanel/",
  },
];
